%YAML:1.0

# pyrimid
pyrimid.levels_num: 4
pyrimid.scale: 0.5

#run
fps: 10

#feature
features.expected_nums: 100
features.init_min_threshold: 50
features.tracking_min_threshold: 50

#mappoint
mappoint.init_min_threshold: 50

